[2022-09-30 01:08:16.889] [remoteagent] [info] Extension host agent started.
[2022-09-30 01:08:17.431] [remoteagent] [info] [127.0.0.1][b006811b][ManagementConnection] New connection established.
[2022-09-30 01:08:17.441] [remoteagent] [info] [127.0.0.1][02fcf2fd][ExtensionHostConnection] New connection established.
[2022-09-30 01:08:17.446] [remoteagent] [info] [127.0.0.1][02fcf2fd][ExtensionHostConnection] <14575> Launched Extension Host Process.
[2022-09-30 01:08:43.374] [remoteagent] [info] [127.0.0.1][b006811b][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-09-30 01:08:43.409] [remoteagent] [info] [127.0.0.1][02fcf2fd][ExtensionHostConnection] <14575> Extension Host Process exited with code: 0, signal: null.
[2022-09-30 01:08:43.409] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-09-30 01:08:51.586] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-09-30 01:08:51.586] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-30 01:08:52.014] [remoteagent] [info] [127.0.0.1][891ab92e][ManagementConnection] New connection established.
[2022-09-30 01:08:52.179] [remoteagent] [info] [127.0.0.1][172f5134][ExtensionHostConnection] New connection established.
[2022-09-30 01:08:52.184] [remoteagent] [info] [127.0.0.1][172f5134][ExtensionHostConnection] <14735> Launched Extension Host Process.
[2022-09-30 01:08:54.065] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-09-30 01:09:02.546] [remoteagent] [info] [127.0.0.1][891ab92e][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-09-30 01:09:02.560] [remoteagent] [info] [127.0.0.1][172f5134][ExtensionHostConnection] <14735> Extension Host Process exited with code: 0, signal: null.
[2022-09-30 01:09:02.561] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-30 01:09:02.561] [remoteagent] [info] Last EH closed, waiting before shutting down
[2022-09-30 01:09:05.738] [remoteagent] [info] Got delay-shutdown request while in shutdown timeout, delaying
[2022-09-30 01:09:05.738] [remoteagent] [info] Cancelling previous shutdown timeout
[2022-09-30 01:09:06.149] [remoteagent] [info] [127.0.0.1][31083c77][ManagementConnection] New connection established.
[2022-09-30 01:09:06.405] [remoteagent] [info] [127.0.0.1][2cdbad59][ExtensionHostConnection] New connection established.
[2022-09-30 01:09:06.421] [remoteagent] [info] [127.0.0.1][2cdbad59][ExtensionHostConnection] <14888> Launched Extension Host Process.
[2022-09-30 01:09:08.363] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/home/clouduser/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
